### PR TITLE
Update k3d create commands

### LINKED ISSUE #7637: Gateway broken on K3d
### Steps to reproduce

- Run the project as a Dev Container, using a prepared k3d Kubernetes environment. (or a Codespace)
  - There's a DevContainer in the provided repo.
- Deploy [this file](https://github.com/loekd/radius-demos/blob/main/06-Gateway/app.bicep)
- Use `curl` to fetch resources at port 80 from the `nginx` Service (works):
  - image
- Use `curl` to try and fetch resources from one of the api services (does not work)
    ```code
    curl http://localhost/blue/api/color/
    <html>
    <head><title>404 Not Found</title></head>
    <body>
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.25.5</center>
    </body>
    </html>

    curl http://localhost/api/color/
    <html>
    <head><title>404 Not Found</title></head>
    <body>
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.25.5</center>
    </body>
    </html>

    ```
  - The nginx Service receives the request, not the `blue` or `green` API. 

### Observed behavior

Gateway does not work.

### Desired behavior

Gateway resource should work in the recommended way of [Getting Started](https://docs.radapp.io/getting-started/). 

### Workaround

Use docker desktop K8s or AKS. Gateway does work over there.

Docker Desktop:
```code
curl  http://localhost/api/color   
green

curl  http://localhost/blue/api/color/
blue

 curl  http://localhost
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
...
```

### rad Version

```
RELEASE   VERSION   BICEP     COMMIT
0.34.0    v0.34.0   0.34.0    0fd82e7eaa9388fead4ea76cb9137ba2a225a236
```

### Operating system

Windows11 running WSL Dev Container based on `mcr.microsoft.com/devcontainers/base:bullseye`

### Additional context

_No response_

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12414](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12414)

### PR DESCRIPTION
**Pull request by brooke-hamilton**
## Description

This PR updates the commands used for creating a k3d cluster by adding a parameter to `k3d cluster create` to disable the default load balancer. The default load balancer was conflicting with the load balancer deployed by Radius. See the issue reference linked below for details.

Note: `traefik@server:0` was changed to `traefik@server:*` to indicate that all instances should be affected, not just the one at index zero.

## Issue reference

Fixes: https://github.com/radius-project/radius/issues/7637

### CODE REVIEW

**Review by sk593 — APPROVED** [review]
LGTM pending a comment on why this was disabled (same thing as this [PR](https://github.com/radius-project/recipes/pull/71#discussion_r1714292137))

**Comment by brooke-hamilton** [comment]
> LGTM pending a comment on why this was disabled (same thing as this [PR](https://github.com/radius-project/recipes/pull/71#discussion_r1714292137))

Done! Thank you! 🚀

**Comment by sk593** [comment]
I pushed some changes to the edge branch of the repo so that might be the cause for the test failures. Should this branch target edge instead so the PR includes up those changes? @Reshrahim

**Comment by brooke-hamilton** [comment]
> I pushed some changes to the edge branch of the repo so that might be the cause for the test failures. Should this branch target edge instead so the PR includes up those changes? @Reshrahim

OK I will switch the PR to target the edge branch. Thank you!

**Review by lakshmimsft — APPROVED** [review]

**Pull request merged**
