### PR TITLE
Add command to automate issue assignment

### PR DESCRIPTION
**Pull request by kachawla**
Adding support for `/assign` command to manage assignment of issue. Copied over from Radius repo https://github.com/radius-project/radius/blob/main/.github/scripts/radius-bot.js.

### CODE REVIEW

**Comment by brooke-hamilton** [comment]
Would we also need to copy `radius-project/radius/.github/workflows/radius-bot.yaml` to this repo?

Should we put the `radius-bot.js` file in the root `radius-project/.github` repo and put the `radius-bot.yaml` file in each repo?

Related to #1641

**Comment by kachawla** [comment]
> Would we also need to copy `radius-project/radius/.github/workflows/radius-bot.yaml` to this repo?

Ah yes, the workflow needs to be copied over as well, thanks for catching that. I'll update the PR.

> Should we put the `radius-bot.js` file in the root `radius-project/.github` repo and put the `radius-bot.yaml` file in each repo?

Based on https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types I gathered that only limited types of files can be applied org wide through `.github` repo. But my understanding on this is limited, so let me know if that's not the case. Not a fan of copying the same file in multiple repo :)

> Related to #1641

Thanks for sharing! Assigned myself to it.

**Comment by kachawla** [comment]
> > Would we also need to copy `radius-project/radius/.github/workflows/radius-bot.yaml` to this repo?
> 
> Ah yes, the workflow needs to be copied over as well, thanks for catching that. I'll update the PR.

@brooke-hamilton Updated

**Review by ytimocin — APPROVED** [review]

**Review by Reshrahim — APPROVED** [review]

**Comment by brooke-hamilton** [comment]
This PR is good. 🚀

**Pull request merged**
